services:
  kafka1:
    image: confluentinc/cp-kafka:7.9.0
    hostname: kafka1
    ports:
      - "9092:9092"  # Expose kafka1 client port
      - "9093:9093"  # Expose kafka1 controller port
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT://kafka1:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093,2@kafka2:9093
      KAFKA_CLUSTER_ID: my-cluster-id
    volumes:
      - ./kafka-data/node1:/var/lib/kafka/data  # Host path

  kafka2:
    image: confluentinc/cp-kafka:7.9.0
    hostname: kafka2
    ports:
      - "9094:9092"  # Expose kafka2 client port
      - "9095:9093"  # Expose kafka2 controller port
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 2
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9094,PLAINTEXT://kafka2:9095
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093,2@kafka2:9093
      KAFKA_CLUSTER_ID: my-cluster-id
    volumes:
      - ./kafka-data/node2:/var/lib/kafka/data  # Host path

volumes:
  kafka1-data:
  kafka2-data:
